# fly.toml app configuration file generated for tour-pods on 2025-04-24T06:41:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tour-pods'
primary_region = 'sjc'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[env]
  DATABASE_URL = 'sqlite3:///data/production.sqlite3'
  PORT = '8080'

[processes]
  app = './bin/rake litestream:run ./bin/rails server'
  worker = '/.bin/jobs'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[services]]
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['worker']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

